In [ ]:
import pandas as pd

value_n_list = ["Andres", "Felipe", "John"]
print(value_n_list)

value_w_list = [50, 78, 91.5]
value_h_list = [1.76, 1.87, 1.69]

data_dic = {"name": value_n_list,
            "weight": value_w_list,
            "height": value_h_list
}

print(data_dic)

df = pd.DataFrame(data_dic)
print(df)

['Andres', 'Felipe', 'John']
{'name': ['Andres', 'Felipe', 'John'], 'weight': [50, 78, 91.5], 'height': [1.76, 1.87, 1.69]}
     name  weight  height
0  Andres    50.0    1.76
1  Felipe    78.0    1.87
2    John    91.5    1.69